spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/CJW?serverTimeZone=Asia/Seoul
#    username: cjw
#    password: 4879
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  main:
#    allow-bean-definition-overriding: true
# h2 Console을 사용하기 위해 com.cjw.toy.config.DataSourceConfig를 설정하는 것 대신
# 기본으로 제공하는 @AutoConfiguration을 파악하고 사용하면 더 효율적이다.
#  h2:
#    console:
#      enabled: true
datasource:
  url: jdbc:h2:mem:db
# Value Anotation 테스트
#property:
#  test:
#    name: Value versus ConfigurationProperties
#propertyTest: Test
#propertyTestList: Test1,Test2,Test3
# ConfigurationProperties 테스트
#fruit:
#  list:
#    - name: banana
#      color: yellow
#    - name: apple
#      color: red
#    - name: water melon
#      color: green

