spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 760654424172-3e4fibsgv2gdk1ocekb73c0g1q5vod88.apps.googleusercontent.com
            client-secret: oyB7ux5jJUgStVekKKGqegTy
          facebook:
            client-id: 219207806478101
            client-secret: c04fcf8795b904ceeaf119432596b7df

custom:
  oauth2:
    kakao:
      client-id: 075158d59c2a3d6afcb142a6ea26feee
      client-secret: tsvOjEPq9hQpwFppQFyAtM1dRxGX3uLG