spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/CJW?serverTimeZone=Asia/Seoul
    username: cjw
    password: 4879
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
property:
  test:
    name: Value versus ConfigurationProperties
propertyTest: Test
propertyTestList: Test1, Test2, Test3
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TES?serverTimeZone=Asia/Seoul
    username: null
    password: null
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: prod

