spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CJW?serverTimeZone=Asia/Seoul
    username: cjw
    password: 4879
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
